Web/FoiCoreApi/Controllers/PanelController.cs
using FoiCoreApi.Classes;
using FoiCoreApi.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WebMatrix.WebData;

namespace FoiCoreApi.Controllers
{
    [SimpleAuthorize]
    public class PanelController : Controller
    {
        //
        // GET: /Panel/

        DBModel db = new DBModel();

        public async Task<ActionResult> Index()
        {
            return await Task.Factory.StartNew<ActionResult>(() =>
            {

                IEnumerable<description> descriptions = db.description.ToList<description>();

                return View(descriptions);

            });

        }

        public ActionResult Edit(int id)
        {

            var desc = db.description.Where<description>(x => x.id == id).FirstOrDefault<description>();

            var sight = db.sight.Where<sight>(x => x.id == desc.sight).FirstOrDefault<sight>();

            var allLanguages = from row in db.language select new SelectListItem { Value = row.id.ToString(), Text = row.name };

            Dictionary<string, object> dictionary = new Dictionary<string, object>();

            dictionary.Add("basic", new decbylang
            {
                id = desc.id,
                name = desc.name,
                desc_short = desc.desc_short,
                language = desc.language,
                lattitude = sight.lattitude,
                longitude = sight.longitude,
                img_thumb = sight.img_thumb,
                img_1 = sight.img_1,
                img_2 = sight.img_2,
                img_3 = sight.img_3
            });

            dictionary.Add("languages", allLanguages);

            //System.Windows.Forms.MessageBox.Show(((decbylang)dictionary["basic"]).name);

            return View(dictionary);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public string Update(decbylang data)
        {
            var desc = db.description.FirstOrDefault<description>(x => x.id == data.id); // u session stavi id poslje da nebi prek hiddena neko mjenjo

            var sig = db.sight.FirstOrDefault<sight>(x => x.id == desc.sight);

            desc.language = data.language;

            desc.name = data.name;

            desc.desc_short = data.desc_short;

            sig.lattitude = data.lattitude;

            sig.longitude = data.longitude;

            sig.img_thumb = data.img_thumb;

            sig.img_1 = data.img_1;

            sig.img_2 = data.img_2;

            sig.img_3 = data.img_3;

            db.SaveChanges();

            return JsonConvert.SerializeObject(new { status = true });

        }

        public string Delete(int id)
        {
            try
            {
                var desc = db.description.FirstOrDefault<description>(x => x.id == id);

                db.sight.Remove(db.sight.FirstOrDefault<sight>(x => x.id == desc.sight));

                //db.SaveChanges();

                db.description.Remove(desc);

                db.SaveChanges();

                return JsonConvert.SerializeObject(new { status = true });
            }
            catch (Exception e)
            {

                return JsonConvert.SerializeObject(new { status = false });

            }

        }

        public ActionResult New()
        {

            var languages = (from row in db.language
                             select new SelectListItem
                             {

                                 Value = row.id.ToString(),
                                 Text = row.name

                             }).ToList<SelectListItem>();

            return View(languages);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public string Insert(decbylang data)
        {
            var id = new sight
            {
                id = 0,
                lattitude = data.lattitude,
                longitude = data.longitude,
                img_thumb = data.img_thumb,
                img_1 = data.img_1,
                img_2 = data.img_2,
                img_3 = data.img_3
            };

            db.sight.Add(id);

            db.SaveChanges();

            db.description.Add(new description
            {
                name = data.name,
                desc_short = data.desc_short,
                language = data.language,
                sight = id.id
            });

            db.SaveChanges();

            return JsonConvert.SerializeObject(data);

        }

    }
}

Web/FoiCoreApi/Views/Panel/Edit.cshtml
@{
    Layout = null;
}
@using FoiCoreApi.Models;
@model Dictionary<string,object>
<form id="edit_form" action="@Url.Action("Edit","Panel")" method="post">

    @Html.Label("name", "Ime znamenitosti:")

    @Html.TextBox("name", (Model["basic"] as decbylang).name, new { name = "name" })

    @Html.Label("desc_short", "Kratki opis:")

    @Html.TextBox("desc_short", (Model["basic"] as decbylang).desc_short, new { name = "desc_short" })

    @Html.Label("lattitude", "Širina:")

    @Html.TextBox("lattitude", string.Format("{0:0.0#####}",((decbylang)Model["basic"]).lattitude), new { name = "lattitude" })

    @Html.Label("longitude", "Dužina:")

    @Html.TextBox("longitude", string.Format("{0:0.0#####}",((decbylang)Model["basic"]).longitude), new { name = "longitude" })

    @Html.Label("img_thumb", "Thumb slika:")

    @Html.TextBox("img_thumb", ((decbylang)Model["basic"]).img_thumb, new { name = "img_thumb" })

    @Html.Label("img_1", "Slika 1:")

    @Html.TextBox("img_1", ((decbylang)Model["basic"]).img_1, new { name = "img_1" })

    @Html.Label("img_2", "Slika 2:")

    @Html.TextBox("img_2", ((decbylang)Model["basic"]).img_2, new { name = "img_2" })

    @Html.Label("img_3", "Slika 3:")

    @Html.TextBox("img_3", ((decbylang)Model["basic"]).img_3, new { name = "img_3" })

    @Html.DropDownList("language", (Model["languages"] as IEnumerable<SelectListItem>), new { name = "language" })

    @Html.TextBox("id", ((decbylang)Model["basic"]).id, new { type="hidden", name = "id" })

    @Html.AntiForgeryToken()

    @Html.TextBox("sub_button", "Promjeni", new { type = "submit" })

</form>

Web/FoiCoreApi/Views/Panel/Index.cshtml
@{
    Layout = null;
}
@using FoiCoreApi.Models;
@model IEnumerable<description>
@{var hreflink = string.Empty;}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link href="~/Css/foundation.min.css" rel="stylesheet" />
    <link href="~/Css/normalize.css" rel="stylesheet" />
    <link href="~/Css/style.css" rel="stylesheet" />
</head>
<body>
    <div>
        <div class="width">
            <a class="button width2" href="/Panel/New" data-reveal-id="new" data-reveal-ajax="true">
                Nova znamenitost
            </a>
            <a class="button width-logout" href="/Account/Logout/">
                Odjava
            </a>
        </div>
        <dl id="descriptions" class="accordion width" data-accordion>
            @foreach (description desc in Model)
            {
                hreflink = "desc" + desc.id.ToString();
                <dd class="">
                    <a href="#@hreflink">@desc.name</a>
                    <div id="@hreflink" class="content ">
                        <a href="/Panel/Edit/@desc.id" class="button" data-reveal-id="edit" data-reveal-ajax="true">
                            Promjeni
                        </a>
                        <a href="/Panel/Delete/@desc.id" class="button delete">
                            Briši
                        </a>
                    </div>
                </dd>
            }
        </dl>
        <div id="new" class="reveal-modal" data-reveal></div>
        <div id="edit" class="reveal-modal" data-reveal></div>
    </div>
    <script src="~/js/jquery-2.1.1.min.js"></script>
    <script src="~/js/foundation.min.js"></script>
    <script src="~/js/custom/panel.min.js"></script>
    <script type="text/javascript">

        $(function () {

            startUp();

        });


    </script>
</body>
</html>

Web/FoiCoreApi/Views/Panel/New.cshtml
@{
    Layout = null;
}
@using FoiCoreApi.Models;
@model IEnumerable<SelectListItem>

@using(Html.BeginForm("Insert", "Panel", FormMethod.Post, new { id = "new_sight" })){
    
    @Html.Label("name", "Ime znamenitosti:")

    @Html.TextBox("name", null, new { name = "name", placeholder = "Ime znamenosti" })
    
    @Html.Label("desc_short", "Opis znamenosti:")

    @Html.TextBox("desc_short", null, new { name = "desc_short", placeholder = "Opis znamenosti" })
    
    @Html.Label("lattitude", "Širina:")

    @Html.TextBox("lattitude", null, new { name = "lattitude", placeholder = "46,773213" })
    
    @Html.Label("longitude", "Visina:")

    @Html.TextBox("longitude", null, new { name = "longitude", placeholder = "16,634314" })
    
    @Html.Label("img_thumb", "Thumb slika:")

    @Html.TextBox("img_thumb", null, new { name = "img_thumb", placeholder = "Thumb slika" })
    
    @Html.Label("img_1", "Slika 1:")

    @Html.TextBox("img_1", null, new { name = "img_1", placeholder = "Slika 1" })
    
    @Html.Label("img_2", "Slika 2:")

    @Html.TextBox("img_2", null, new { name = "img_2", placeholder = "Slika 2" })
    
    @Html.Label("img_3", "Slika 3:")

    @Html.TextBox("img_3", null, new { name = "img_3", placeholder = "Slika 3" })
    
    @Html.Label("language", "Jezik:")
    
    @Html.DropDownList("language", Model, new { name = "language" })
    
    @Html.AntiForgeryToken()
    
    @Html.TextBox("sub_button", "Kreiraj", new { type = "submit" })

}